language: python

python:
  - "3.6"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install coverage
  - pip install coveralls
  - pip install scikit-learn
  - pip install quantulum3

script:
  - coverage run --source=quantulum3 --omit="*test*" setup.py test
  - coverage report

after_success:
  - coveralls